### ISSUE TITLE
[US-05] Product details

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#11]
## Value Statement (User Story)

As a user I want to see additional information about a product when I click on it.

## Description

![product-details](https://user-images.githubusercontent.com/89028737/136559574-e6877a3f-4d9e-4ee9-b0fb-9b129c879f73.png)

## Acceptance Criteria

- [x] When the user clicks on a product card, the details page of the product is shown
- [x] The details page shows additional information about the product

## Tasks

- [x] Create feature branch
- [x] Add new data to the mock data array if necessary
- [x] Build DetailsPage component
- [x] Add the new component to the App.js along with a route
- [x] Write a test for the new component
- [x] Optional: Add back button to return to the previous page

## Complexity
Medium
