### ISSUE TITLE
[US-15] Product data in database

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#24]
## Value Statement (User Story)

As a user I want to be able to see the same products in different sessions.

## Description

Set up a database for the product data, so that the app can be used in multiple sessions with the same data and changes are kept in a database.

## Acceptance Criteria

- [x] The product data should be stored in a database so that changes can be kept

## Tasks

- [x] Create feature branch
- [x] Set up mongodb
- [x] Update file structure
- [x] Add collection of products in mongodb
- [x] Display product data from mongodb in the app

## Complexity

Medium
