### ISSUE TITLE
[US-16] Add, edit and delete products

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#25]
## Value Statement (User Story)

As a user I want to be able to add products to the list as well as update and delete them.

## Description

The changes made in one session should be stored and also accessible without local storage in the next sessions.

## Acceptance Criteria

- [ ] Users should be able to add products, update and delete them
- [ ] Changes should be stored in the database and accessible from other devices/sessions

## Tasks

- [ ] Create feature branch
- [ ] Write add, edit and delete requests
- [ ] Add requests to existing functions
- [ ] Update tests of changed components
- [ ] Update storybook files of modified components

## Complexity

Medium
