### ISSUE TITLE
[US-17] Recipe data

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#26]
## Value Statement ( User Story)

As a user I want to be able to access the same recipes from multiple devices.

## Description

The updated recipe data should be accessible independent from local storage.

## Acceptance Criteria

- [ ] The recipe data should be stored in the database

## Tasks

- [ ] Create feature branch
- [ ] Create collection in mongodb for recipe data
- [ ] Set up add, delete and edit requests for recipes
- [ ] Call requests in existing functions
- [ ] Update tests for changed components
- [ ] Update storybook files for changed components

## Complexity

Medium
