### ISSUE TITLE
[US-12] Recipe Form

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#29]
## Value Statement (User Story)

As a user I want to be able to add new recipes to the list using a form.

## Description

![recipe-form](https://user-images.githubusercontent.com/89028737/139652943-4740b412-c37f-4e10-889b-ffd631f8db81.png)

## Acceptance Criteria

- [x] The form should have four different input fields.
- [x] When the form is submitted, the new recipe should be added to the recipe list.

## Tasks

- [x] Create feature branch
- [x] Build RecipeForm component
- [x] Write handleSubmit function which adds the new recipe to the product list
- [x] Write a test for the RecipeForm component
- [x] Add storybook file for the new component
- [x] Add RecipeForm component to App.js along with a new route
- [x] Add styling to the new component

## Complexity

Low
