### ISSUE TITLE
[US-13] Readme

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#32]
## Value Statement (User Story)

As a user I want to find information about the app in the README.md file.

## Description

The README.md should provide the user with information about the app.

## Acceptance Criteria

- [x] The README.md contains screenshots, a description, the tech stack and a project setup guide.

## Tasks

- [x] Create feature branch
- [x] Write README.md file

## Complexity

Low
