### ISSUE TITLE
[US-02] Product form

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#4]
## Value Statement (User Story)

As a user I want to be able to add new products to the list using a form.

## Description

![form-component](https://user-images.githubusercontent.com/89028737/136402064-034cc5e6-a176-4959-9d47-4b8f7f0f9cce.png)

## Acceptance Criteria

- [x] The form should have at least five different input fields.
- [x] When the form is submitted, the new product should be added to the product list.

## Tasks

- [x] Create feature branch
- [x] Build Form component
- [x] Write handleSubmit function which adds the new product to the product list
- [x] Write a test for the Form component
- [x] Add Form component to App.js along with a new route
- [x] Add styling to the new component

## Complexity

Medium
