### ISSUE TITLE
[US-06] Filter by category

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#5]
## Value Statement (User Story)

As a user I want to be able to filter the products by category.

## Description

![filter-function](https://user-images.githubusercontent.com/89028737/136519193-db546509-eaf2-44de-b1c2-bc5a1e3424e4.png)

## Acceptance Criteria

- [x] A filter button should appear on top of the page
- [x] The filter button should open a dropdown menu with different categories
- [x] When clicking on one of the categories, the product list should show products from that category

## Tasks

- [x] Create feature branch
- [x] Build FilterButton component
- [x] Add FilterButton to product list page
- [x] Create dropdown menu with categories
- [x] Write filter function
- [x] Add filter function on click to the categories
- [x] Write test for the new component

## Complexity
Medium
