### ISSUE TITLE
[US-04] Add button/ link to form

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#6]
## Value Statement (User Story)

As a user, I want to be able to access the product form by clicking a button on the products page.

## Description

![addItem-button](https://user-images.githubusercontent.com/89028737/136524872-7dfbf61a-2ee2-468d-8242-8f3dd94ffece.png)

## Acceptance Criteria

- [x] A button should be visible on the product list page.
- [x] When clicking the button, the user should be redirected to the product form.

## Tasks

- [x] Create feature branch
- [x] Build Button component
- [x] Write function that handles the button click
- [x] Add Button to the product list page
- [x] Write test for the new component

## Complexity

Low
