### ISSUE TITLE
[US-07] Star reviews

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#7]
## Value Statement (User Story)

As a user I want to be able to review a product by clicking on star icons.

## Description

![star-reviews](https://user-images.githubusercontent.com/89028737/136530997-70abf48f-2e4f-44e4-9d33-6250134cc257.png)

## Acceptance Criteria

- [ ] Five stars should be visible on every card on the product list.
- [ ] When clicking on one of the stars, all of the stars up to that one should change color, indicating a review.

## Tasks

- [x] Add feature branch
- [x] Build Review component
- [x] Add useState for reviews to the App.js
- [ ] Write function to update useState and change color when a star is clicked
- [ ] Write a test for the new component
- [ ] Add Review component to ProductCard component

## Complexity

Medium
