### ISSUE TITLE
[US-10] Links between products and recipes

### ISSUE THREAD

**Issue by mortaen** [mortaen/capstone-project#9]
## Value Statement (User Story)

As a user I want to be able to click on a recipe or an ingredient and get redirected to the corresponding page.

## Description

![links](https://user-images.githubusercontent.com/89028737/136556900-cd884be3-ccf7-4868-9fc9-902a4957f089.png)

## Acceptance Criteria

- [x] When an ingredient or a recipe name is clicked, the user gets redirected to the corresponding page
- [x] It has to be visible to the user which ingredients are clickable

## Tasks

- [x] Create feature branch
- [x] Add links to ingredients/products and recipes that are present in the app
- [x] Highlight the names which can be clicked
- [ ] Optional: Write a function that automatically adds links to newly added items
- [x] Add a test to the RecipeCard tests to determine whether the links work

## Complexity
Low
